
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Maria Joaquina",
    "email": "marimay@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "f0b3c829-2f72-40f9-95d8-fee2b9b58b39"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "123",
    "account_id_to": "321",
    "amount": 5
}